[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.19.4",
    "streamlit-folium>=0.24.0",
    "streamlit>=1.42.2",
    "plotly>=6.0.0",
    "gpxpy>=1.6.2",
    "trafilatura>=2.0.0",
]
